root: true
env:
  node: true
  es6: true

ignorePatterns:
  - node_modules/*
  - build/*
  - coverage/*
  - example/*
  - tsdown.config.ts

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 2022
  project: './tsconfig.json'

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/stylistic
  - plugin:eslint-comments/recommended
  - plugin:prettier/recommended

plugins:
  - eslint-comments
  - '@typescript-eslint'

rules:
  camelcase: warn
  '@typescript-eslint/no-unused-vars':
    - warn
    - args: none
      varsIgnorePattern: '^_'
      argsIgnorePattern: '^_'
  prefer-const:
    - error
    - destructuring: any
      ignoreReadBeforeAssign: false
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/no-var-requires': off
  '@typescript-eslint/ban-ts-comment': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/consistent-type-definitions': off
  '@typescript-eslint/consistent-indexed-object-style': off
  '@typescript-eslint/no-require-imports': off
# TODO(agent): migrate to the flat eslint.config.js format so we can drop the
# ESLINT_USE_FLAT_CONFIG shim once TypeScript rules are fully modernized.
